import pytest
from unittest.mock import MagicMock, patch
from fastapi.testclient import TestClient
import sys

# --- MOCKING EXTERNAL SERVICES ---
mock_pc_module = MagicMock()
mock_pc_instance = MagicMock()
mock_pc_instance.list_indexes.return_value.names.return_value = ["FAQ"]
mock_pc_module.Pinecone.return_value = mock_pc_instance

mock_vs_module = MagicMock()
mock_chat_module = MagicMock()
mock_embeddings_module = MagicMock()

# Apply patches to sys.modules
with patch.dict("sys.modules", {
    "pinecone": mock_pc_module,
    "langchain_pinecone": mock_vs_module,
    "langchain_openai": mock_chat_module,
    "langchain_community.embeddings": mock_embeddings_module,
}):
    # FIX 1: Import the module as 'app_module' instead of just 'app'
    # This lets us access the file variables (like rag_graph) separately from the FastAPI app
    import main as app_module

# FIX 2: Initialize client using the app inside the module
client = TestClient(app_module.app)

# --- TESTS ---

def test_index_stats():
    """Test the /index/state endpoint"""
    response = client.get("/index/state")
    assert response.status_code == 200
    assert "total_vectorstore" in response.json()

def test_query_rag_mocked():
    """Test the /query endpoint with a mocked graph response"""
    
    # FIX 3: Patch 'rag_graph' on the MODULE (app_module), not the FastAPI instance
    with patch.object(app_module, "rag_graph") as mock_graph:
        
        # Configure the mock to return our fake data
        mock_graph.ainvoke.return_value = {
            "query": "rewritten query",
            "answer": "This is a mocked answer generated by tests.",
            "documents": [
                MagicMock(page_content="Mock content", metadata={"filename": "test.pdf"})
            ]
        }

        payload = {"query": "What is in the document?", "session_id": "test-123"}
        response = client.post("/query", json=payload)

        # Debugging: Print error if it fails
        if response.status_code != 200:
            print(response.json())

        assert response.status_code == 200
        data = response.json()
        assert data["answer"] == "This is a mocked answer generated by tests."
        assert data["num_source_used"] == 1